/****************************************************************************
 * arch/arm/src/mcx-nxxx/hardware/n947/n947_dmamux.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_MCX_NXXX_HARDWARE_N947_N947_DMAMUX_H
#define __ARCH_ARM_SRC_MCX_NXXX_HARDWARE_N947_N947_DMAMUX_H

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* MCX Nxxx does not use the older standalone DMAMUX_CHCFG register block.
 * Instead each eDMA channel owns a CH_MUX[SRC] field.  This compatibility
 * header keeps the same request-source names used by the existing UART/I2C
 * driver code and by other NXP ports.
 *
 * Plain request values allocate from DMA0 first and fall back to DMA1 if
 * DMA0 is full.  Use N947_DMA_REQUEST(1, source) to force DMA1.
 */

#define N947_DMA_REQUEST_SOURCE_MASK       0x7f
#define N947_DMA_REQUEST_CONTROLLER_SHIFT  8
#define N947_DMA_REQUEST_CONTROLLER_MASK   (1u << N947_DMA_REQUEST_CONTROLLER_SHIFT)

#define N947_DMA_REQUEST(ctrl, source) \
  ((((uint32_t)(ctrl) & 1) << N947_DMA_REQUEST_CONTROLLER_SHIFT) | \
   ((uint32_t)(source) & N947_DMA_REQUEST_SOURCE_MASK))

#define N947_DMA_REQUEST_SOURCE(req) \
  ((uint32_t)(req) & N947_DMA_REQUEST_SOURCE_MASK)

#define N947_DMA_REQUEST_CONTROLLER(req) \
  (((uint32_t)(req) & N947_DMA_REQUEST_CONTROLLER_MASK) >> \
   N947_DMA_REQUEST_CONTROLLER_SHIFT)

/* Common MCX Nxxx eDMA request sources.  Values match the NXP MCXN947 SDK
 * dma_request_source_t enum.  DMA0 and DMA1 use the same source numbers.
 */

#define DMA_REQUEST_MUXSOFTWARE          0
#define DMA_REQUEST_MUXFLEXSPI0RX          1
#define DMA_REQUEST_MUXFLEXSPI0TX          2
#define DMA_REQUEST_MUXPINT0               3
#define DMA_REQUEST_MUXPINT1               4
#define DMA_REQUEST_MUXPINT2               5
#define DMA_REQUEST_MUXPINT3               6
#define DMA_REQUEST_MUXCTIMER0M0           7
#define DMA_REQUEST_MUXCTIMER0M1           8
#define DMA_REQUEST_MUXCTIMER1M0           9
#define DMA_REQUEST_MUXCTIMER1M1           10
#define DMA_REQUEST_MUXCTIMER2M0           11
#define DMA_REQUEST_MUXCTIMER2M1           12
#define DMA_REQUEST_MUXCTIMER3M0           13
#define DMA_REQUEST_MUXCTIMER3M1           14
#define DMA_REQUEST_MUXCTIMER4M0           15
#define DMA_REQUEST_MUXCTIMER4M1           16
#define DMA_REQUEST_MUXWUU0                17
#define DMA_REQUEST_MUXMICFIL0             18
#define DMA_REQUEST_MUXSCT0DMA0            19
#define DMA_REQUEST_MUXSCT0DMA1            20
#define DMA_REQUEST_MUXADC0FIFOAREQ        21
#define DMA_REQUEST_MUXADC0FIFOBREQ        22
#define DMA_REQUEST_MUXADC1FIFOAREQ        23
#define DMA_REQUEST_MUXADC1FIFOBREQ        24
#define DMA_REQUEST_MUXDAC0FIFO            25
#define DMA_REQUEST_MUXDAC1FIFO            26
#define DMA_REQUEST_MUXDAC2FIFO            27
#define DMA_REQUEST_MUXHSCMP0              28
#define DMA_REQUEST_MUXHSCMP1              29
#define DMA_REQUEST_MUXHSCMP2              30
#define DMA_REQUEST_MUXEVTG0OUT0A          31
#define DMA_REQUEST_MUXEVTG0OUT0B          32
#define DMA_REQUEST_MUXEVTG0OUT1A          33
#define DMA_REQUEST_MUXEVTG0OUT1B          34
#define DMA_REQUEST_MUXEVTG0OUT2A          35
#define DMA_REQUEST_MUXEVTG0OUT2B          36
#define DMA_REQUEST_MUXEVTG0OUT3A          37
#define DMA_REQUEST_MUXEVTG0OUT3B          38
#define DMA_REQUEST_MUXFLEXPWM0CAPT0       39
#define DMA_REQUEST_MUXFLEXPWM0CAPT1       40
#define DMA_REQUEST_MUXFLEXPWM0CAPT2       41
#define DMA_REQUEST_MUXFLEXPWM0CAPT3       42
#define DMA_REQUEST_MUXFLEXPWM0VAL0        43
#define DMA_REQUEST_MUXFLEXPWM0VAL1        44
#define DMA_REQUEST_MUXFLEXPWM0VAL2        45
#define DMA_REQUEST_MUXFLEXPWM0VAL3        46
#define DMA_REQUEST_MUXFLEXPWM1CAPT0       47
#define DMA_REQUEST_MUXFLEXPWM1CAPT1       48
#define DMA_REQUEST_MUXFLEXPWM1CAPT2       49
#define DMA_REQUEST_MUXFLEXPWM1CAPT3       50
#define DMA_REQUEST_MUXFLEXPWM1VAL0        51
#define DMA_REQUEST_MUXFLEXPWM1VAL1        52
#define DMA_REQUEST_MUXFLEXPWM1VAL2        53
#define DMA_REQUEST_MUXFLEXPWM1VAL3        54
#define DMA_REQUEST_MUXLPTMR0              57
#define DMA_REQUEST_MUXLPTMR1              58
#define DMA_REQUEST_MUXFLEXCAN0            59
#define DMA_REQUEST_MUXFLEXCAN1            60
#define DMA_REQUEST_MUXFLEXIO0SHIFT0       61
#define DMA_REQUEST_MUXFLEXIO0SHIFT1       62
#define DMA_REQUEST_MUXFLEXIO0SHIFT2       63
#define DMA_REQUEST_MUXFLEXIO0SHIFT3       64
#define DMA_REQUEST_MUXFLEXIO0SHIFT4       65
#define DMA_REQUEST_MUXFLEXIO0SHIFT5       66
#define DMA_REQUEST_MUXFLEXIO0SHIFT6       67
#define DMA_REQUEST_MUXFLEXIO0SHIFT7       68

#define DMA_REQUEST_MUXLPFLEXCOMM0RX       69
#define DMA_REQUEST_MUXLPFLEXCOMM0TX       70
#define DMA_REQUEST_MUXLPFLEXCOMM1RX       71
#define DMA_REQUEST_MUXLPFLEXCOMM1TX       72
#define DMA_REQUEST_MUXLPFLEXCOMM2RX       73
#define DMA_REQUEST_MUXLPFLEXCOMM2TX       74
#define DMA_REQUEST_MUXLPFLEXCOMM3RX       75
#define DMA_REQUEST_MUXLPFLEXCOMM3TX       76
#define DMA_REQUEST_MUXLPFLEXCOMM4RX       77
#define DMA_REQUEST_MUXLPFLEXCOMM4TX       78
#define DMA_REQUEST_MUXLPFLEXCOMM5RX       79
#define DMA_REQUEST_MUXLPFLEXCOMM5TX       80
#define DMA_REQUEST_MUXLPFLEXCOMM6RX       81
#define DMA_REQUEST_MUXLPFLEXCOMM6TX       82
#define DMA_REQUEST_MUXLPFLEXCOMM7RX       83
#define DMA_REQUEST_MUXLPFLEXCOMM7TX       84
#define DMA_REQUEST_MUXLPFLEXCOMM8RX       85
#define DMA_REQUEST_MUXLPFLEXCOMM8TX       86
#define DMA_REQUEST_MUXLPFLEXCOMM9RX       87
#define DMA_REQUEST_MUXLPFLEXCOMM9TX       88

#define DMA_REQUEST_MUXEMVSIM0RX           91
#define DMA_REQUEST_MUXEMVSIM0TX           92
#define DMA_REQUEST_MUXEMVSIM1RX           93
#define DMA_REQUEST_MUXEMVSIM1TX           94
#define DMA_REQUEST_MUXI3C0RX              95
#define DMA_REQUEST_MUXI3C0TX              96
#define DMA_REQUEST_MUXI3C1RX              97
#define DMA_REQUEST_MUXI3C1TX              98
#define DMA_REQUEST_MUXSAI0RX              99
#define DMA_REQUEST_MUXSAI0TX              100
#define DMA_REQUEST_MUXSAI1RX              101
#define DMA_REQUEST_MUXSAI1TX              102
#define DMA_REQUEST_MUXSINC0               103
#define DMA_REQUEST_MUXSINC1               104
#define DMA_REQUEST_MUXSINC2               105
#define DMA_REQUEST_MUXSINC3               106
#define DMA_REQUEST_MUXSINC4               107
#define DMA_REQUEST_MUXGPIO0PIN0           108
#define DMA_REQUEST_MUXGPIO0PIN1           109
#define DMA_REQUEST_MUXGPIO1PIN0           110
#define DMA_REQUEST_MUXGPIO1PIN1           111
#define DMA_REQUEST_MUXGPIO2PIN0           112
#define DMA_REQUEST_MUXGPIO2PIN1           113
#define DMA_REQUEST_MUXGPIO3PIN0           114
#define DMA_REQUEST_MUXGPIO3PIN1           115
#define DMA_REQUEST_MUXGPIO4PIN0           116
#define DMA_REQUEST_MUXGPIO4PIN1           117
#define DMA_REQUEST_MUXGPIO5PIN0           118
#define DMA_REQUEST_MUXGPIO5PIN1           119
#define DMA_REQUEST_MUXTSI0ENDOFSCAN       120
#define DMA_REQUEST_MUXTSI0OUTOFRANGE      121

/* UART/I2C/SPI compatibility aliases.  On MCX Nxxx all three modes share
 * the LP_FLEXCOMM RX/TX DMA request for the corresponding instance.
 */

#define DMA_REQUEST_MUXLPUART0RX           DMA_REQUEST_MUXLPFLEXCOMM0RX
#define DMA_REQUEST_MUXLPUART0TX           DMA_REQUEST_MUXLPFLEXCOMM0TX
#define DMA_REQUEST_MUXLPUART1RX           DMA_REQUEST_MUXLPFLEXCOMM1RX
#define DMA_REQUEST_MUXLPUART1TX           DMA_REQUEST_MUXLPFLEXCOMM1TX
#define DMA_REQUEST_MUXLPUART2RX           DMA_REQUEST_MUXLPFLEXCOMM2RX
#define DMA_REQUEST_MUXLPUART2TX           DMA_REQUEST_MUXLPFLEXCOMM2TX
#define DMA_REQUEST_MUXLPUART3RX           DMA_REQUEST_MUXLPFLEXCOMM3RX
#define DMA_REQUEST_MUXLPUART3TX           DMA_REQUEST_MUXLPFLEXCOMM3TX
#define DMA_REQUEST_MUXLPUART4RX           DMA_REQUEST_MUXLPFLEXCOMM4RX
#define DMA_REQUEST_MUXLPUART4TX           DMA_REQUEST_MUXLPFLEXCOMM4TX
#define DMA_REQUEST_MUXLPUART5RX           DMA_REQUEST_MUXLPFLEXCOMM5RX
#define DMA_REQUEST_MUXLPUART5TX           DMA_REQUEST_MUXLPFLEXCOMM5TX
#define DMA_REQUEST_MUXLPUART6RX           DMA_REQUEST_MUXLPFLEXCOMM6RX
#define DMA_REQUEST_MUXLPUART6TX           DMA_REQUEST_MUXLPFLEXCOMM6TX
#define DMA_REQUEST_MUXLPUART7RX           DMA_REQUEST_MUXLPFLEXCOMM7RX
#define DMA_REQUEST_MUXLPUART7TX           DMA_REQUEST_MUXLPFLEXCOMM7TX
#define DMA_REQUEST_MUXLPUART8RX           DMA_REQUEST_MUXLPFLEXCOMM8RX
#define DMA_REQUEST_MUXLPUART8TX           DMA_REQUEST_MUXLPFLEXCOMM8TX
#define DMA_REQUEST_MUXLPUART9RX           DMA_REQUEST_MUXLPFLEXCOMM9RX
#define DMA_REQUEST_MUXLPUART9TX           DMA_REQUEST_MUXLPFLEXCOMM9TX

#define DMA_REQUEST_MUXLPI2C0RX            DMA_REQUEST_MUXLPFLEXCOMM0RX
#define DMA_REQUEST_MUXLPI2C0TX            DMA_REQUEST_MUXLPFLEXCOMM0TX
#define DMA_REQUEST_MUXLPI2C1RX            DMA_REQUEST_MUXLPFLEXCOMM1RX
#define DMA_REQUEST_MUXLPI2C1TX            DMA_REQUEST_MUXLPFLEXCOMM1TX
#define DMA_REQUEST_MUXLPI2C2RX            DMA_REQUEST_MUXLPFLEXCOMM2RX
#define DMA_REQUEST_MUXLPI2C2TX            DMA_REQUEST_MUXLPFLEXCOMM2TX
#define DMA_REQUEST_MUXLPI2C3RX            DMA_REQUEST_MUXLPFLEXCOMM3RX
#define DMA_REQUEST_MUXLPI2C3TX            DMA_REQUEST_MUXLPFLEXCOMM3TX
#define DMA_REQUEST_MUXLPI2C4RX            DMA_REQUEST_MUXLPFLEXCOMM4RX
#define DMA_REQUEST_MUXLPI2C4TX            DMA_REQUEST_MUXLPFLEXCOMM4TX
#define DMA_REQUEST_MUXLPI2C5RX            DMA_REQUEST_MUXLPFLEXCOMM5RX
#define DMA_REQUEST_MUXLPI2C5TX            DMA_REQUEST_MUXLPFLEXCOMM5TX
#define DMA_REQUEST_MUXLPI2C6RX            DMA_REQUEST_MUXLPFLEXCOMM6RX
#define DMA_REQUEST_MUXLPI2C6TX            DMA_REQUEST_MUXLPFLEXCOMM6TX
#define DMA_REQUEST_MUXLPI2C7RX            DMA_REQUEST_MUXLPFLEXCOMM7RX
#define DMA_REQUEST_MUXLPI2C7TX            DMA_REQUEST_MUXLPFLEXCOMM7TX
#define DMA_REQUEST_MUXLPI2C8RX            DMA_REQUEST_MUXLPFLEXCOMM8RX
#define DMA_REQUEST_MUXLPI2C8TX            DMA_REQUEST_MUXLPFLEXCOMM8TX

#define DMA_REQUEST_MUXLPSPI0RX            DMA_REQUEST_MUXLPFLEXCOMM0RX
#define DMA_REQUEST_MUXLPSPI0TX            DMA_REQUEST_MUXLPFLEXCOMM0TX
#define DMA_REQUEST_MUXLPSPI1RX            DMA_REQUEST_MUXLPFLEXCOMM1RX
#define DMA_REQUEST_MUXLPSPI1TX            DMA_REQUEST_MUXLPFLEXCOMM1TX
#define DMA_REQUEST_MUXLPSPI2RX            DMA_REQUEST_MUXLPFLEXCOMM2RX
#define DMA_REQUEST_MUXLPSPI2TX            DMA_REQUEST_MUXLPFLEXCOMM2TX
#define DMA_REQUEST_MUXLPSPI3RX            DMA_REQUEST_MUXLPFLEXCOMM3RX
#define DMA_REQUEST_MUXLPSPI3TX            DMA_REQUEST_MUXLPFLEXCOMM3TX
#define DMA_REQUEST_MUXLPSPI4RX            DMA_REQUEST_MUXLPFLEXCOMM4RX
#define DMA_REQUEST_MUXLPSPI4TX            DMA_REQUEST_MUXLPFLEXCOMM4TX
#define DMA_REQUEST_MUXLPSPI5RX            DMA_REQUEST_MUXLPFLEXCOMM5RX
#define DMA_REQUEST_MUXLPSPI5TX            DMA_REQUEST_MUXLPFLEXCOMM5TX
#define DMA_REQUEST_MUXLPSPI6RX            DMA_REQUEST_MUXLPFLEXCOMM6RX
#define DMA_REQUEST_MUXLPSPI6TX            DMA_REQUEST_MUXLPFLEXCOMM6TX
#define DMA_REQUEST_MUXLPSPI7RX            DMA_REQUEST_MUXLPFLEXCOMM7RX
#define DMA_REQUEST_MUXLPSPI7TX            DMA_REQUEST_MUXLPFLEXCOMM7TX
#define DMA_REQUEST_MUXLPSPI8RX            DMA_REQUEST_MUXLPFLEXCOMM8RX
#define DMA_REQUEST_MUXLPSPI8TX            DMA_REQUEST_MUXLPFLEXCOMM8TX
#define DMA_REQUEST_MUXLPSPI9RX            DMA_REQUEST_MUXLPFLEXCOMM9RX
#define DMA_REQUEST_MUXLPSPI9TX            DMA_REQUEST_MUXLPFLEXCOMM9TX

#endif /* __ARCH_ARM_SRC_MCX_NXXX_HARDWARE_N947_N947_DMAMUX_H */
