abufsrc@Music=outputs=1:map=1[Music0],
alsasrc@pcm0c=devname=pcm0c:outputs=1:map=1:format=s16:sample_rate=44100:ch_layout=mono[Capture0],
[Music0]alsasink@pcm0p=inputs=1:devname=pcm0p:format=s16:sample_rate=44100:ch_layout=mono,
[Capture0]abufsink@Capture=inputs=1
